### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Alex1602** [glytchtech/ESPCam#1]
Hi there, Nice small project. 

One small question, do you use the regular source for this project or do you have a better source for this?

Regards,
Alex

**Comment by DSAutomations** [comment]
He's using ESPHome as the firmware, you would need to use his configuration file [cam1.yaml](https://github.com/glytchtech/ESPCam/blob/master/cam1.yaml) along with a board flashed with ESPHome to get this up and running.  Check [this guide](https://esphome.io/guides/getting_started_command_line.html#) for more info

**Comment by Alex1602** [comment]
Ah thanks
